[package]
name = "archive_books"
version = "0.0.1"
edition = "2021"

[dependencies]
colored = "2"
clap = { version = "4", features = ["derive"] }
chrono = "0.4"
serde_json = "1"
serde = { version = "1", features = ["derive"] }